### PR TITLE
Upgrade to Django 1.10-style middleware

### PR DESCRIPTION
**Pull request by urtzai**

### CODE REVIEW

**Comment by staticdev** [comment]
@urtzai TravisCI is signaling backwards compatibility breaks in this new import for older versions than 1.10: ImportError: cannot import name 'MiddlewareMixin'

**Comment by urtzai** [comment]
Great! This is ready :D

**Comment by shadiakiki1986** [comment]
in the readme, you might need to replace the usage of `TEMPLATE_CONTEXT_PROCESSORS` with the usage of `TEMPLATES` array e.g.:
```
TEMPLATES = [
    {   
        'BACKEND': 'django.template.backends.django.DjangoTemplates', 
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # pagination configuration
                # https://github.com/staticdev/django-pagination-bootstrap#configuration
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
            ],
        },
    },
]
```

**Comment by urtzai** [comment]
But this change will cause incompatibilities in Django 1.6 and 1.7 versions: https://travis-ci.org/staticdev/django-pagination-bootstrap/builds/209286312

**Comment by shadiakiki1986** [comment]
True. Maybe a section for pre-1.8 and another for post-1.8?

**Comment by staticdev** [comment]
@urtzai I think you have a point. I've merged it anyway.
@shadiakiki1986 I would appreciate very much that.

**Pull request merged**
