### PR TITLE
Django 1.9 Compatibility

### PR DESCRIPTION
**Pull request by urtzai**
Django 1.9 Compatibility

### CODE REVIEW

**Comment by avelis** [comment]
+1
For merging the pull request. Sadly I think this repo looks quite lonely without any recent contributions.

**Comment by staticdev** [comment]
Merge complete!

**Comment by avelis** [comment]
Awesome! :tada:

**Comment by urtzai** [comment]
Thank you Thiago!

**Comment by urtzai** [comment]
Hi! I would appreciate to have a new pypi package (1.0.8) with those new merges. Thank you!

**Comment by staticdev** [comment]
@urtzai done! (it is 1.0.9, since I had some trouble with de readme).

**Pull request merged**
